server:
  port: 8481

spring:
  dubbo:
    application:
      name: server-provider
    base-package: com.ztc.latte.service.impl
    registry:
      address: 127.0.0.1
      port: 2181
    consumer:
      timeout: 10000
      check: false
      retries: 0
    protocol:
      name: dubbo
      port: 21882
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/latte_manager?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.ztc.latte.server.model

logging:
  level:
    com.ztc.lottery.server.service.mapper: debug