server:
  port: 8481

spring:
  dubbo:
    application:
      name: server-provider
    base-package: com.ztc.latte.service.impl
    registry:
      address: 127.0.0.1                   # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/latte_manager?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.ztc.latte.server.model

logging:
  level:
    com.ztc.lottery.server.service.mapper: debug