server:
  port: 8480

spring:
  dubbo:
    application:
      name: server-consumer
    base-package: com.ztc.latte.web.controller
    registry:
      address: 127.0.0.1
      port: 2181
    consumer:
      timeout: 10000
      check: false
      retries: 0
    protocol:
      name: dubbo
      port: 21881
  redis:
    host: 118.24.238.244
    port: 6379
    password: pudrtsns1cqc8o9w
    database: 0
    timeout: 1000
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0